ktor:
  application:
    modules:
      - dev.hennie.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  privateKey: ${JWT_PRIVATE_KEY}
  issuer: ${JWT_ISSUER}
  audience: ${JWT_AUDIENCE}
  realm: ${JWT_REALM:my_realm}
storage:
  driver: ${DB_DRIVER:org.h2.Driver}
  url: ${DB_URL:jdbc:h2:mem:test;DB_CLOSE_DELAY=-1}
  user: ${DB_USER:root}
  password: ${DB_PASSWORD:}
